version: "3.7"
services:
  file_transfer:
    container_name: file_transfer
    build:
      context: .
      target: development
    env_file:
      - env/docker.env
    ports:
      # ${SERVER_PORT_DOCKER} is defined in root .env file and
      # is the same as ${SERVER_PORT} defined in docker.env
      - ${SERVER_PORT_DOCKER}:${SERVER_PORT_DOCKER}
      - 9229:9229
    command: npm run start:dev
    networks:
      - file_transfer_net
    depends_on:
      - redis
      - minio
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  redis:
    container_name: redis
    image: redis:alpine
    env_file:
      - env/docker.env
    ports:
      - ${REDIS_PORT}
    volumes:
      - ./volumes/redis/data:/data
    networks:
      - file_transfer_net

  minio:
    container_name: minio
    image: minio/minio
    env_file:
      - env/docker.env
    command: server /data/minio
    ports:
      - ${MINIO_PORT}:${MINIO_PORT}
    volumes:
      - ./volumes/minio/data:/minio/data
    networks:
      - file_transfer_net

networks:
  file_transfer_net:
